[package]
name = "neobridge-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
hex_color = "3.0.0"
mouse_position = "0.1.3"
serde = "1.0.197"
serde_json = "1.0.115"
serialport = "4.3.0"
windows = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
   
] }
